# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore HealthyBusiness.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: .NET Lint
      uses: zyactions/dotnet-lint@v1
      with:
        workspace: TheBradgeCompany.csproj
        implicit-restore: true
      
